#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t burnmannotebook \
                         -C "start_jupyter -t -T @tool table_of_contents.ipynb" \
                         -u anaconda-7 \
                         -r none
